link:
  tutorial_link: "https://www.railstutorial.org/"
  learn_link: "https://www.learnenough.com/"
  book_link: "https://www.railstutorial.org/book"
  series_link: "https://screencasts.railstutorial.org/"
  ror_link: "https://rubyonrails.org/"
  help_link: "https://www.railstutorial.org/help"
  contact_link: "https://www.railstutorial.org/contact"
  news_link: "https://news.railstutorial.org/"
  author_link: "https://www.michaelhartl.com/"
user:
  email:
    length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  name:
    length: 50
  password:
    length: 6
