link:
  tutorial_link: "https://www.railstutorial.org/"
  learn_link: "https://www.learnenough.com/"
  book_link: "https://www.railstutorial.org/book"
  series_link: "https://screencasts.railstutorial.org/"
  ror_link: "https://rubyonrails.org/"
  help_link: "https://www.railstutorial.org/help"
  contact_link: "https://www.railstutorial.org/contact"
