link:
  tutorial_link: "https://www.railstutorial.org/"
  learn_link: "https://www.learnenough.com/"
  book_link: "https://www.railstutorial.org/book"
  series_link: "https://screencasts.railstutorial.org/"
  ror_link: "https://rubyonrails.org/"
  help_link: "https://www.railstutorial.org/help"
  contact_link: "https://www.railstutorial.org/contact"
  news_link: "https://news.railstutorial.org/"
  author_link: "https://www.michaelhartl.com/"
  gravatar_link: "http://gravatar.com/emails"
user:
  email:
    length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  name:
    length: 50
  password:
    length: 6
  gravatar:
    size: 80
    size_post: 50
per_page: 10
session:
  remember: "1"
time_expired: 10
post:
  length: 140
  size: 5
  m_size: 500
  file_image: [image/jpeg, image/gif, image/png]
